// Built-in song library. Used when Spotify credentials are not configured.
export const LIBRARY = [
  { id: 'lib0000', name: 'Blinding Lights', artist: 'The Weeknd' },
  { id: 'lib0001', name: 'Dreams', artist: 'Fleetwood Mac' },
  { id: 'lib0002', name: 'Teenage Dirtbag', artist: 'Wheatus' },
  { id: 'lib0003', name: 'Redbone', artist: 'Childish Gambino' },
  { id: 'lib0004', name: 'Cranes in the Sky', artist: 'Solange' },
  { id: 'lib0005', name: 'Nightcall', artist: 'Kavinsky' },
  { id: 'lib0006', name: 'Motion Sickness', artist: 'Phoebe Bridgers' },
  { id: 'lib0007', name: 'Pyramids', artist: 'Frank Ocean' },
  { id: 'lib0008', name: 'Ivy', artist: 'Frank Ocean' },
  { id: 'lib0009', name: 'Nikes', artist: 'Frank Ocean' },
  { id: 'lib0010', name: 'Self Control', artist: 'Frank Ocean' },
  { id: 'lib0011', name: 'Thinkin Bout You', artist: 'Frank Ocean' },
  { id: 'lib0012', name: 'This Must Be the Place', artist: 'Talking Heads' },
  { id: 'lib0013', name: 'Once in a Lifetime', artist: 'Talking Heads' },
  { id: 'lib0014', name: 'Alright', artist: 'Kendrick Lamar' },
  { id: 'lib0015', name: 'Money Trees', artist: 'Kendrick Lamar' },
  { id: 'lib0016', name: 'Sing About Me', artist: 'Kendrick Lamar' },
  { id: 'lib0017', name: 'Fade Into You', artist: 'Mazzy Star' },
  { id: 'lib0018', name: 'Vienna', artist: 'Billy Joel' },
  { id: 'lib0019', name: 'Passionfruit', artist: 'Drake' },
  { id: 'lib0020', name: 'Marvins Room', artist: 'Drake' },
  { id: 'lib0021', name: 'Weightless', artist: 'Marconi Union' },
  { id: 'lib0022', name: 'Two Weeks', artist: 'FKA twigs' },
  { id: 'lib0023', name: 'Harvest Moon', artist: 'Neil Young' },
  { id: 'lib0024', name: 'Bad Habit', artist: 'Steve Lacy' },
  { id: 'lib0025', name: 'Dark Red', artist: 'Steve Lacy' },
  { id: 'lib0026', name: 'Runaway', artist: 'Kanye West' },
  { id: 'lib0027', name: 'Flashing Lights', artist: 'Kanye West' },
  { id: 'lib0028', name: 'Devil in a New Dress', artist: 'Kanye West' },
  { id: 'lib0029', name: 'Time', artist: 'Pink Floyd' },
  { id: 'lib0030', name: 'Wish You Were Here', artist: 'Pink Floyd' },
  { id: 'lib0031', name: 'Comfortably Numb', artist: 'Pink Floyd' },
  { id: 'lib0032', name: 'Karma Police', artist: 'Radiohead' },
  { id: 'lib0033', name: 'Let Down', artist: 'Radiohead' },
  { id: 'lib0034', name: 'Weird Fishes', artist: 'Radiohead' },
  { id: 'lib0035', name: 'No Surprises', artist: 'Radiohead' },
  { id: 'lib0036', name: 'Nude', artist: 'Radiohead' },
  { id: 'lib0037', name: 'Everything In Its Right Place', artist: 'Radiohead' },
  { id: 'lib0038', name: 'Space Song', artist: 'Beach House' },
  { id: 'lib0039', name: 'Myth', artist: 'Beach House' },
  { id: 'lib0040', name: 'Silver Soul', artist: 'Beach House' },
  { id: 'lib0041', name: 'Sunflower', artist: 'Post Malone' },
  { id: 'lib0042', name: 'Circles', artist: 'Post Malone' },
  { id: 'lib0043', name: 'Chamber of Reflection', artist: 'Mac DeMarco' },
  { id: 'lib0044', name: 'My Kind of Woman', artist: 'Mac DeMarco' },
  { id: 'lib0045', name: 'Ode to Viceroy', artist: 'Mac DeMarco' },
  { id: 'lib0046', name: 'Somebody Else', artist: 'The 1975' },
  { id: 'lib0047', name: 'Robbers', artist: 'The 1975' },
  { id: 'lib0048', name: 'About You', artist: 'The 1975' },
  { id: 'lib0049', name: 'Electric Feel', artist: 'MGMT' },
  { id: 'lib0050', name: 'Time to Pretend', artist: 'MGMT' },
  { id: 'lib0051', name: 'Kids', artist: 'MGMT' },
  { id: 'lib0052', name: 'Do I Wanna Know', artist: 'Arctic Monkeys' },
  { id: 'lib0053', name: '505', artist: 'Arctic Monkeys' },
  { id: 'lib0054', name: 'R U Mine', artist: 'Arctic Monkeys' },
  { id: 'lib0055', name: 'Why\'d You Only Call Me When You\'re High', artist: 'Arctic Monkeys' },
  { id: 'lib0056', name: 'The Less I Know The Better', artist: 'Tame Impala' },
  { id: 'lib0057', name: 'Let It Happen', artist: 'Tame Impala' },
  { id: 'lib0058', name: 'New Person Same Old Mistakes', artist: 'Tame Impala' },
  { id: 'lib0059', name: 'Eventually', artist: 'Tame Impala' },
  { id: 'lib0060', name: 'Sweet Disposition', artist: 'The Temper Trap' },
  { id: 'lib0061', name: 'Midnight City', artist: 'M83' },
  { id: 'lib0062', name: 'Wait', artist: 'M83' },
  { id: 'lib0063', name: 'Take Care', artist: 'Beach House' },
  { id: 'lib0064', name: 'Hotline Bling', artist: 'Drake' },
  { id: 'lib0065', name: 'One Dance', artist: 'Drake' },
  { id: 'lib0066', name: 'Location', artist: 'Khalid' },
  { id: 'lib0067', name: 'Young Dumb & Broke', artist: 'Khalid' },
  { id: 'lib0068', name: 'Sunday Best', artist: 'Surfaces' },
  { id: 'lib0069', name: 'Best Part', artist: 'Daniel Caesar' },
  { id: 'lib0070', name: 'Get You', artist: 'Daniel Caesar' },
  { id: 'lib0071', name: 'Japanese Denim', artist: 'Daniel Caesar' },
  { id: 'lib0072', name: 'Come Through and Chill', artist: 'Miguel' },
  { id: 'lib0073', name: 'Adorn', artist: 'Miguel' },
  { id: 'lib0074', name: 'Sure Thing', artist: 'Miguel' },
  { id: 'lib0075', name: 'Cellophane', artist: 'FKA twigs' },
  { id: 'lib0076', name: 'Video Games', artist: 'Lana Del Rey' },
  { id: 'lib0077', name: 'Summertime Sadness', artist: 'Lana Del Rey' },
  { id: 'lib0078', name: 'Young and Beautiful', artist: 'Lana Del Rey' },
  { id: 'lib0079', name: 'Ride', artist: 'Lana Del Rey' },
  { id: 'lib0080', name: 'Norman Rockwell', artist: 'Lana Del Rey' },
  { id: 'lib0081', name: 'Vienna Waits for You', artist: 'Billy Joel' },
  { id: 'lib0082', name: 'Piano Man', artist: 'Billy Joel' },
  { id: 'lib0083', name: 'Landslide', artist: 'Fleetwood Mac' },
  { id: 'lib0084', name: 'The Chain', artist: 'Fleetwood Mac' },
  { id: 'lib0085', name: 'Rhiannon', artist: 'Fleetwood Mac' },
  { id: 'lib0086', name: 'Everywhere', artist: 'Fleetwood Mac' },
  { id: 'lib0087', name: 'Go Your Own Way', artist: 'Fleetwood Mac' },
  { id: 'lib0088', name: 'Heroes', artist: 'David Bowie' },
  { id: 'lib0089', name: 'Space Oddity', artist: 'David Bowie' },
  { id: 'lib0090', name: 'Life on Mars', artist: 'David Bowie' },
  { id: 'lib0091', name: 'Under Pressure', artist: 'Queen' },
  { id: 'lib0092', name: 'Bohemian Rhapsody', artist: 'Queen' },
  { id: 'lib0093', name: 'A Case of You', artist: 'Joni Mitchell' },
  { id: 'lib0094', name: 'River', artist: 'Joni Mitchell' },
  { id: 'lib0095', name: 'Both Sides Now', artist: 'Joni Mitchell' },
  { id: 'lib0096', name: 'Pink Moon', artist: 'Nick Drake' },
  { id: 'lib0097', name: 'Northern Sky', artist: 'Nick Drake' },
  { id: 'lib0098', name: 'The Night We Met', artist: 'Lord Huron' },
  { id: 'lib0099', name: 'Ends of the Earth', artist: 'Lord Huron' },
  { id: 'lib0100', name: 'Holocene', artist: 'Bon Iver' },
  { id: 'lib0101', name: 'Skinny Love', artist: 'Bon Iver' },
  { id: 'lib0102', name: 're: Stacks', artist: 'Bon Iver' },
  { id: 'lib0103', name: 'Flume', artist: 'Bon Iver' },
  { id: 'lib0104', name: '715 - CRΣΣKS', artist: 'Bon Iver' },
  { id: 'lib0105', name: 'First Day of My Life', artist: 'Bright Eyes' },
  { id: 'lib0106', name: 'Lua', artist: 'Bright Eyes' },
  { id: 'lib0107', name: 'Such Great Heights', artist: 'The Postal Service' },
  { id: 'lib0108', name: 'Brand New Colony', artist: 'The Postal Service' },
  { id: 'lib0109', name: 'Transatlanticism', artist: 'Death Cab for Cutie' },
  { id: 'lib0110', name: 'Soul Meets Body', artist: 'Death Cab for Cutie' },
  { id: 'lib0111', name: 'I Will Follow You into the Dark', artist: 'Death Cab for Cutie' },
  { id: 'lib0112', name: 'Float On', artist: 'Modest Mouse' },
  { id: 'lib0113', name: 'The World at Large', artist: 'Modest Mouse' },
  { id: 'lib0114', name: 'Maps', artist: 'Yeah Yeah Yeahs' },
  { id: 'lib0115', name: 'Heads Will Roll', artist: 'Yeah Yeah Yeahs' },
  { id: 'lib0116', name: 'Last Nite', artist: 'The Strokes' },
  { id: 'lib0117', name: 'Someday', artist: 'The Strokes' },
  { id: 'lib0118', name: 'Reptilia', artist: 'The Strokes' },
  { id: 'lib0119', name: 'Under Cover of Darkness', artist: 'The Strokes' },
  { id: 'lib0120', name: 'The Adults Are Talking', artist: 'The Strokes' },
  { id: 'lib0121', name: 'Mr. Brightside', artist: 'The Killers' },
  { id: 'lib0122', name: 'When You Were Young', artist: 'The Killers' },
  { id: 'lib0123', name: 'Take Me Out', artist: 'Franz Ferdinand' },
  { id: 'lib0124', name: 'Dog Days Are Over', artist: 'Florence + The Machine' },
  { id: 'lib0125', name: 'Shake It Out', artist: 'Florence + The Machine' },
  { id: 'lib0126', name: 'Cosmic Love', artist: 'Florence + The Machine' },
  { id: 'lib0127', name: 'Genesis', artist: 'Grimes' },
  { id: 'lib0128', name: 'Oblivion', artist: 'Grimes' },
  { id: 'lib0129', name: 'Cola', artist: 'Lana Del Rey' },
  { id: 'lib0130', name: 'Motion Picture Soundtrack', artist: 'Radiohead' },
  { id: 'lib0131', name: 'Bloom', artist: 'The Paper Kites' },
  { id: 'lib0132', name: 'Featherstone', artist: 'The Paper Kites' },
  { id: 'lib0133', name: 'Sea of Love', artist: 'Cat Power' },
  { id: 'lib0134', name: 'The Greatest', artist: 'Cat Power' },
  { id: 'lib0135', name: 'Between the Bars', artist: 'Elliott Smith' },
  { id: 'lib0136', name: 'Angeles', artist: 'Elliott Smith' },
  { id: 'lib0137', name: 'Say Yes', artist: 'Elliott Smith' },
  { id: 'lib0138', name: 'Waltz #2', artist: 'Elliott Smith' },
  { id: 'lib0139', name: 'Miss Misery', artist: 'Elliott Smith' },
  { id: 'lib0140', name: 'Heavenly Father', artist: 'Bon Iver' },
  { id: 'lib0141', name: 'Scott Street', artist: 'Phoebe Bridgers' },
  { id: 'lib0142', name: 'Funeral', artist: 'Phoebe Bridgers' },
  { id: 'lib0143', name: 'Kyoto', artist: 'Phoebe Bridgers' },
  { id: 'lib0144', name: 'Garden Song', artist: 'Phoebe Bridgers' },
  { id: 'lib0145', name: 'I Know the End', artist: 'Phoebe Bridgers' },
  { id: 'lib0146', name: 'Chinatown', artist: 'Bleachers' },
  { id: 'lib0147', name: 'Nikes on My Feet', artist: 'Mac Miller' },
  { id: 'lib0148', name: 'Good News', artist: 'Mac Miller' },
  { id: 'lib0149', name: 'Self Care', artist: 'Mac Miller' },
  { id: 'lib0150', name: '2009', artist: 'Mac Miller' },
  { id: 'lib0151', name: 'Come Back to Earth', artist: 'Mac Miller' },
  { id: 'lib0152', name: 'Ladders', artist: 'Mac Miller' },
  { id: 'lib0153', name: 'Sunflower Vol 6', artist: 'Harry Styles' },
  { id: 'lib0154', name: 'Falling', artist: 'Harry Styles' },
  { id: 'lib0155', name: 'As It Was', artist: 'Harry Styles' },
  { id: 'lib0156', name: 'Watermelon Sugar', artist: 'Harry Styles' },
  { id: 'lib0157', name: 'Fine Line', artist: 'Harry Styles' },
  { id: 'lib0158', name: 'Cardigan', artist: 'Taylor Swift' },
  { id: 'lib0159', name: 'August', artist: 'Taylor Swift' },
  { id: 'lib0160', name: 'This Is Me Trying', artist: 'Taylor Swift' },
  { id: 'lib0161', name: 'All Too Well', artist: 'Taylor Swift' },
  { id: 'lib0162', name: 'Style', artist: 'Taylor Swift' },
  { id: 'lib0163', name: 'Cruel Summer', artist: 'Taylor Swift' },
  { id: 'lib0164', name: 'Pink + White', artist: 'Frank Ocean' },
  { id: 'lib0165', name: 'Seigfried', artist: 'Frank Ocean' },
  { id: 'lib0166', name: 'White Ferrari', artist: 'Frank Ocean' },
  { id: 'lib0167', name: 'Godspeed', artist: 'Frank Ocean' },
  { id: 'lib0168', name: 'Solo', artist: 'Frank Ocean' },
  { id: 'lib0169', name: 'Chanel', artist: 'Frank Ocean' },
  { id: 'lib0170', name: 'Sweet Life', artist: 'Frank Ocean' },
  { id: 'lib0171', name: 'Super Rich Kids', artist: 'Frank Ocean' },
  { id: 'lib0172', name: 'The Suburbs', artist: 'Arcade Fire' },
  { id: 'lib0173', name: 'Wake Up', artist: 'Arcade Fire' },
  { id: 'lib0174', name: 'Rebellion', artist: 'Arcade Fire' },
  { id: 'lib0175', name: 'Ready to Start', artist: 'Arcade Fire' },
  { id: 'lib0176', name: 'Sprawl II', artist: 'Arcade Fire' },
  { id: 'lib0177', name: 'Age of Adz', artist: 'Sufjan Stevens' },
  { id: 'lib0178', name: 'Chicago', artist: 'Sufjan Stevens' },
  { id: 'lib0179', name: 'Mystery of Love', artist: 'Sufjan Stevens' },
  { id: 'lib0180', name: 'Should Have Known Better', artist: 'Sufjan Stevens' },
  { id: 'lib0181', name: 'Death with Dignity', artist: 'Sufjan Stevens' },
  { id: 'lib0182', name: 'Fourth of July', artist: 'Sufjan Stevens' },
  { id: 'lib0183', name: 'Visions of Gideon', artist: 'Sufjan Stevens' },
  { id: 'lib0184', name: 'Motion', artist: 'Khalid' },
  { id: 'lib0185', name: 'Nothing\'s Gonna Hurt You Baby', artist: 'Cigarettes After Sex' },
  { id: 'lib0186', name: 'Apocalypse', artist: 'Cigarettes After Sex' },
  { id: 'lib0187', name: 'K.', artist: 'Cigarettes After Sex' },
  { id: 'lib0188', name: 'Sunsetz', artist: 'Cigarettes After Sex' },
  { id: 'lib0189', name: 'Cry', artist: 'Cigarettes After Sex' },
  { id: 'lib0190', name: 'Only in My Dreams', artist: 'The Marias' },
  { id: 'lib0191', name: 'Hush', artist: 'The Marias' },
  { id: 'lib0192', name: 'Cariño', artist: 'The Marias' },
  { id: 'lib0193', name: 'Un Alma', artist: 'The Marias' },
  { id: 'lib0194', name: 'Palace', artist: 'The Marias' },
  { id: 'lib0195', name: 'Sofia', artist: 'Clairo' },
  { id: 'lib0196', name: 'Bags', artist: 'Clairo' },
  { id: 'lib0197', name: 'Pretty Girl', artist: 'Clairo' },
  { id: 'lib0198', name: 'Amoeba', artist: 'Clairo' },
  { id: 'lib0199', name: 'Blouse', artist: 'Clairo' },
  { id: 'lib0200', name: 'Sexy to Someone', artist: 'Clairo' },
  { id: 'lib0201', name: 'Sailor Song', artist: 'Gigi Perez' },
  { id: 'lib0202', name: 'Lovers Rock', artist: 'TV Girl' },
  { id: 'lib0203', name: 'Not Allowed', artist: 'TV Girl' },
  { id: 'lib0204', name: 'Cigarettes out the Window', artist: 'TV Girl' },
  { id: 'lib0205', name: 'From the Start', artist: 'Laufey' },
  { id: 'lib0206', name: 'Valentine', artist: 'Laufey' },
  { id: 'lib0207', name: 'Falling Behind', artist: 'Laufey' },
  { id: 'lib0208', name: 'Vampire Empire', artist: 'Big Thief' },
  { id: 'lib0209', name: 'Simulation Swarm', artist: 'Big Thief' },
  { id: 'lib0210', name: 'Not', artist: 'Big Thief' },
  { id: 'lib0211', name: 'Paul', artist: 'Big Thief' },
  { id: 'lib0212', name: 'Masterpiece', artist: 'Big Thief' },
  { id: 'lib0213', name: 'Chinese Satellite', artist: 'Phoebe Bridgers' },
  { id: 'lib0214', name: 'Nobody', artist: 'Mitski' },
  { id: 'lib0215', name: 'Washing Machine Heart', artist: 'Mitski' },
  { id: 'lib0216', name: 'Your Best American Girl', artist: 'Mitski' },
  { id: 'lib0217', name: 'First Love / Late Spring', artist: 'Mitski' },
  { id: 'lib0218', name: 'My Love Mine All Mine', artist: 'Mitski' },
  { id: 'lib0219', name: 'Francis Forever', artist: 'Mitski' },
  { id: 'lib0220', name: 'Strawberry Blond', artist: 'Mitski' },
  { id: 'lib0221', name: 'Class of 2013', artist: 'Mitski' },
  { id: 'lib0222', name: 'Two Slow Dancers', artist: 'Mitski' },
  { id: 'lib0223', name: 'Sun Bleached Flies', artist: 'MJ Lenderman' },
  { id: 'lib0224', name: 'Wristwatch', artist: 'MJ Lenderman' },
  { id: 'lib0225', name: 'Silk Chiffon', artist: 'MUNA' },
  { id: 'lib0226', name: 'I Know a Place', artist: 'MUNA' },
  { id: 'lib0227', name: 'Kiss Me', artist: 'Sixpence None the Richer' },
  { id: 'lib0228', name: 'There She Goes', artist: 'The La\'s' },
  { id: 'lib0229', name: 'Linger', artist: 'The Cranberries' },
  { id: 'lib0230', name: 'Dreams', artist: 'The Cranberries' },
  { id: 'lib0231', name: 'Zombie', artist: 'The Cranberries' },
  { id: 'lib0232', name: 'Just Like Heaven', artist: 'The Cure' },
  { id: 'lib0233', name: 'Pictures of You', artist: 'The Cure' },
  { id: 'lib0234', name: 'Lovesong', artist: 'The Cure' },
  { id: 'lib0235', name: 'Boys Don\'t Cry', artist: 'The Cure' },
  { id: 'lib0236', name: 'Friday I\'m in Love', artist: 'The Cure' },
  { id: 'lib0237', name: 'This Charming Man', artist: 'The Smiths' },
  { id: 'lib0238', name: 'There Is a Light That Never Goes Out', artist: 'The Smiths' },
  { id: 'lib0239', name: 'Asleep', artist: 'The Smiths' },
  { id: 'lib0240', name: 'How Soon Is Now', artist: 'The Smiths' },
  { id: 'lib0241', name: 'Please Please Please', artist: 'The Smiths' },
  { id: 'lib0242', name: 'Bizarre Love Triangle', artist: 'New Order' },
  { id: 'lib0243', name: 'Ceremony', artist: 'New Order' },
  { id: 'lib0244', name: 'Blue Monday', artist: 'New Order' },
  { id: 'lib0245', name: 'Love Will Tear Us Apart', artist: 'Joy Division' },
  { id: 'lib0246', name: 'Disorder', artist: 'Joy Division' },
  { id: 'lib0247', name: 'Age of Consent', artist: 'New Order' },
  { id: 'lib0248', name: 'Temptation', artist: 'New Order' },
  { id: 'lib0249', name: 'Dreams', artist: 'Beach House' },
  { id: 'lib0250', name: 'Beach Life-In-Death', artist: 'Car Seat Headrest' },
  { id: 'lib0251', name: 'Drunk Drivers/Killer Whales', artist: 'Car Seat Headrest' },
  { id: 'lib0252', name: 'Sober to Death', artist: 'Car Seat Headrest' },
  { id: 'lib0253', name: 'Cute Thing', artist: 'Car Seat Headrest' },
  { id: 'lib0254', name: 'Fill in the Blank', artist: 'Car Seat Headrest' },
  { id: 'lib0255', name: 'Vampire Weekend', artist: 'A-Punk' },
  { id: 'lib0256', name: 'Oxford Comma', artist: 'Vampire Weekend' },
  { id: 'lib0257', name: 'Campus', artist: 'Vampire Weekend' },
  { id: 'lib0258', name: 'Hannah Hunt', artist: 'Vampire Weekend' },
  { id: 'lib0259', name: 'Step', artist: 'Vampire Weekend' },
  { id: 'lib0260', name: 'Harmony Hall', artist: 'Vampire Weekend' },
  { id: 'lib0261', name: 'Diane Young', artist: 'Vampire Weekend' },
  { id: 'lib0262', name: 'Obvious Bicycle', artist: 'Vampire Weekend' },
  { id: 'lib0263', name: 'Wolves', artist: 'Bon Iver' },
  { id: 'lib0264', name: 'Blood Bank', artist: 'Bon Iver' },
  { id: 'lib0265', name: 'Ribs', artist: 'Lorde' },
  { id: 'lib0266', name: 'Green Light', artist: 'Lorde' },
  { id: 'lib0267', name: 'Liability', artist: 'Lorde' },
  { id: 'lib0268', name: 'Supercut', artist: 'Lorde' },
  { id: 'lib0269', name: 'The Louvre', artist: 'Lorde' },
  { id: 'lib0270', name: 'Perfect Places', artist: 'Lorde' },
  { id: 'lib0271', name: 'Royals', artist: 'Lorde' },
  { id: 'lib0272', name: 'Solar Power', artist: 'Lorde' },
  { id: 'lib0273', name: 'Stoned at the Nail Salon', artist: 'Lorde' },
  { id: 'lib0274', name: 'Nights', artist: 'Frank Ocean' },
  { id: 'lib0275', name: 'Lost', artist: 'Frank Ocean' },
  { id: 'lib0276', name: 'Novacane', artist: 'Frank Ocean' },
  { id: 'lib0277', name: 'Bad Religion', artist: 'Frank Ocean' },
  { id: 'lib0278', name: 'Forrest Gump', artist: 'Frank Ocean' },
  { id: 'lib0279', name: 'Sweater Weather', artist: 'The Neighbourhood' },
  { id: 'lib0280', name: 'Daddy Issues', artist: 'The Neighbourhood' },
  { id: 'lib0281', name: 'Reflections', artist: 'The Neighbourhood' },
  { id: 'lib0282', name: 'Afraid', artist: 'The Neighbourhood' },
  { id: 'lib0283', name: 'Heat Waves', artist: 'Glass Animals' },
  { id: 'lib0284', name: 'Gooey', artist: 'Glass Animals' },
  { id: 'lib0285', name: 'Season 2 Episode 3', artist: 'Glass Animals' },
  { id: 'lib0286', name: 'Take a Slice', artist: 'Glass Animals' },
  { id: 'lib0287', name: 'Tokyo Drifting', artist: 'Glass Animals' },
  { id: 'lib0288', name: 'Electric Love', artist: 'BØRNS' },
  { id: 'lib0289', name: 'Riptide', artist: 'Vance Joy' },
  { id: 'lib0290', name: 'Georgia', artist: 'Vance Joy' },
  { id: 'lib0291', name: 'Ho Hey', artist: 'The Lumineers' },
  { id: 'lib0292', name: 'Ophelia', artist: 'The Lumineers' },
  { id: 'lib0293', name: 'Stubborn Love', artist: 'The Lumineers' },
  { id: 'lib0294', name: 'Little Talks', artist: 'Of Monsters and Men' },
  { id: 'lib0295', name: 'Dirty Paws', artist: 'Of Monsters and Men' },
  { id: 'lib0296', name: 'Skinny Love', artist: 'Birdy' },
  { id: 'lib0297', name: 'Wings', artist: 'Birdy' },
  { id: 'lib0298', name: 'Bloom', artist: 'Radiohead' },
  { id: 'lib0299', name: 'Codex', artist: 'Radiohead' },
  { id: 'lib0300', name: 'Lotus Flower', artist: 'Radiohead' },
  { id: 'lib0301', name: 'Reckoner', artist: 'Radiohead' },
  { id: 'lib0302', name: 'House of Cards', artist: 'Radiohead' },
  { id: 'lib0303', name: '15 Step', artist: 'Radiohead' },
  { id: 'lib0304', name: 'Idioteque', artist: 'Radiohead' },
  { id: 'lib0305', name: 'Pyramid Song', artist: 'Radiohead' },
  { id: 'lib0306', name: 'Paranoid Android', artist: 'Radiohead' },
  { id: 'lib0307', name: 'Fake Plastic Trees', artist: 'Radiohead' },
  { id: 'lib0308', name: 'High and Dry', artist: 'Radiohead' },
  { id: 'lib0309', name: 'Creep', artist: 'Radiohead' },
  { id: 'lib0310', name: 'Exit Music', artist: 'Radiohead' },
  { id: 'lib0311', name: 'Lucky', artist: 'Radiohead' },
  { id: 'lib0312', name: 'Airbag', artist: 'Radiohead' },
  { id: 'lib0313', name: 'Daydreaming', artist: 'Radiohead' },
  { id: 'lib0314', name: 'True Love Waits', artist: 'Radiohead' },
  { id: 'lib0315', name: 'Cigarette Daydreams', artist: 'Cage the Elephant' },
  { id: 'lib0316', name: 'Trouble', artist: 'Cage the Elephant' },
  { id: 'lib0317', name: 'Come a Little Closer', artist: 'Cage the Elephant' },
  { id: 'lib0318', name: 'Ain\'t No Rest for the Wicked', artist: 'Cage the Elephant' },
  { id: 'lib0319', name: 'Feels Like We Only Go Backwards', artist: 'Tame Impala' },
  { id: 'lib0320', name: 'Elephant', artist: 'Tame Impala' },
  { id: 'lib0321', name: 'Yes I\'m Changing', artist: 'Tame Impala' },
  { id: 'lib0322', name: 'Borderline', artist: 'Tame Impala' },
  { id: 'lib0323', name: 'Lost in Yesterday', artist: 'Tame Impala' },
  { id: 'lib0324', name: 'Is It True', artist: 'Tame Impala' },
  { id: 'lib0325', name: 'Breathe Deeper', artist: 'Tame Impala' },
  { id: 'lib0326', name: 'Somebody That I Used to Know', artist: 'Gotye' },
  { id: 'lib0327', name: 'Latch', artist: 'Disclosure' },
  { id: 'lib0328', name: 'You & Me', artist: 'Disclosure' },
  { id: 'lib0329', name: 'Midnight Blue', artist: 'Sam Gellaitry' },
  { id: 'lib0330', name: 'Ferrari', artist: 'Frank Ocean' },
  { id: 'lib0331', name: 'Slide', artist: 'Calvin Harris' },
  { id: 'lib0332', name: 'Feels', artist: 'Calvin Harris' },
  { id: 'lib0333', name: 'Sunflower', artist: 'Rex Orange County' },
  { id: 'lib0334', name: 'Best Friend', artist: 'Rex Orange County' },
  { id: 'lib0335', name: 'Loving Is Easy', artist: 'Rex Orange County' },
  { id: 'lib0336', name: 'Television / So Far So Good', artist: 'Rex Orange County' },
  { id: 'lib0337', name: 'Pluto Projector', artist: 'Rex Orange County' },
  { id: 'lib0338', name: 'It\'s Not the Same Anymore', artist: 'Rex Orange County' },
  { id: 'lib0339', name: 'Nectar', artist: 'Joji' },
  { id: 'lib0340', name: 'Slow Dancing in the Dark', artist: 'Joji' },
  { id: 'lib0341', name: 'Glimpse of Us', artist: 'Joji' },
  { id: 'lib0342', name: 'Sanctuary', artist: 'Joji' },
  { id: 'lib0343', name: 'Run', artist: 'Joji' },
  { id: 'lib0344', name: 'After the Storm', artist: 'Kali Uchis' },
  { id: 'lib0345', name: 'Telepatía', artist: 'Kali Uchis' },
  { id: 'lib0346', name: 'Moonlight', artist: 'Kali Uchis' },
  { id: 'lib0347', name: 'Just a Stranger', artist: 'Kali Uchis' },
  { id: 'lib0348', name: 'Melting', artist: 'Kali Uchis' },
  { id: 'lib0349', name: 'Golden Hour', artist: 'JVKE' },
  { id: 'lib0350', name: 'Snooze', artist: 'SZA' },
  { id: 'lib0351', name: 'Kill Bill', artist: 'SZA' },
  { id: 'lib0352', name: 'Good Days', artist: 'SZA' },
  { id: 'lib0353', name: 'The Weekend', artist: 'SZA' },
  { id: 'lib0354', name: 'Drew Barrymore', artist: 'SZA' },
  { id: 'lib0355', name: 'Love Galore', artist: 'SZA' },
  { id: 'lib0356', name: 'Nobody Gets Me', artist: 'SZA' },
  { id: 'lib0357', name: 'Broken Clocks', artist: 'SZA' },
  { id: 'lib0358', name: 'Supermodel', artist: 'SZA' },
  { id: 'lib0359', name: 'Prom', artist: 'SZA' },
  { id: 'lib0360', name: 'Sober', artist: 'Childish Gambino' },
  { id: 'lib0361', name: '3005', artist: 'Childish Gambino' },
  { id: 'lib0362', name: 'Sweatpants', artist: 'Childish Gambino' },
  { id: 'lib0363', name: 'Feels Like Summer', artist: 'Childish Gambino' },
  { id: 'lib0364', name: 'Me and Your Mama', artist: 'Childish Gambino' },
  { id: 'lib0365', name: 'This Is America', artist: 'Childish Gambino' },
];
